language: php

php:
  - 7.0
  - 5.6
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:

script: 
  - mysql -u root < databaseDocumentation/physical.sql
  - cd site
  - phpunit --bootstrap class/autoload.php tests/

notifications:
  - never
