language: php

php:
  - 7.0
  - 5.6
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - mysql -e 'create database vovoSite;'

script: phpunit --bootstrap site/class/autoload.php site/tests/
