language: php

php:
  - 7.0
  - 5.6
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - mysql -u root < databaseDocumentation/physical.sql

script: phpunit --bootstrap site/class/autoload.php site/tests/
