<?php
	require_once('configuration/globals.php');
	require_once('database/dao.php');
	require_once('html/page.php');
	require_once('model/userModel.php');
	require_once('model/questionModel.php');
	require_once('model/videoModel.php');
	require_once('database/userDAO.php');
	require_once('database/questionDAO.php');
?>
